server:
  port: 8085

spring:
  application:
    name: service-lowcode
  config:
    import: optional:nacos:${spring.application.name}.yml
  datasource:
    url: ${LOWCODE_DB_URL:jdbc:postgresql://localhost:5433/triobase}
    username: ${LOWCODE_DB_USERNAME:triobase}
    password: ${LOWCODE_DB_PASSWORD:triobase123}
    driver-class-name: org.postgresql.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  flyway:
    enabled: false
    locations: classpath:db/migration
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
      config:
        server-addr: localhost:8848
        file-extension: yml

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl

logging:
  level:
    root: DEBUG
    com.triobase: DEBUG
