#!/usr/bin/env python3
"""TrioBase 增量注释治理扫描器。

扫描器只检查可以客观判断的结构与禁止项；注释是否准确表达业务意图仍由评审者负责。
历史问题可写入基线，增量模式只阻断本次变更新增的 BLOCKER/PROHIBITED 问题。
"""

from __future__ import annotations

import argparse
import ast
import json
import os
import re
import subprocess
import sys
import tokenize
from io import StringIO
from dataclasses import asdict, dataclass
from datetime import date
from pathlib import Path


SUPPORTED_SUFFIXES = {".java", ".py", ".ts", ".tsx", ".vue", ".sql", ".yaml", ".yml", ".sh", ".ps1"}
EXCLUDED_PARTS = {
    ".git", ".idea", ".next", ".pnpm-store", ".venv", "archive", "coverage",
    "dist", "generated", "node_modules", "target", "temp_lib", "vendor", "__pycache__",
}
PUBLIC_DECLARATION = re.compile(
    r"^\s*public\s+(?:(?:abstract|final|sealed|non-sealed|static)\s+)*(?:class|interface|enum|record)\s+(?P<name>[A-Za-z_$][\w$]*)"
)
TS_PUBLIC_DECLARATION = re.compile(
    r"^\s*export\s+(?:(?:default|declare|abstract|async)\s+)*(?:class|interface|type|enum|function|const)\s+(?P<name>[A-Za-z_$][\w$]*)"
)
COMMENTED_CODE = re.compile(
    r"^\s*(?://|#)\s*(?:if\s*\(|for\s*\(|while\s*\(|return\s+|throw\s+new\s+|[A-Za-z_$][\w$]*\s*=)"
)
AUTHOR_HISTORY = re.compile(r"(?i)\b(?:author|created\s+by|modified\s+by|修改人|创建人|修改日期)\b")
RESTATEMENT = re.compile(r"^\s*(?://|#)\s*(?:获取|设置|判断|返回|调用|循环|遍历|创建|删除|修改)(?:数据|结果|对象|列表|方法|变量|集合)?\s*$")
SQL_RISKY = re.compile(r"(?im)^\s*(?:create|alter|drop|truncate|update|delete|insert)\b")
SQL_PURPOSE = re.compile(r"(?im)^\s*--\s*(?:目的|purpose)\s*[:：]")
SQL_ROLLBACK = re.compile(r"(?im)^\s*--\s*(?:回滚|rollback)\s*[:：]")
CONFIG_RISK = re.compile(r"(?i)^\s*(?:fail-open|enabled|timeout|ttl|token|secret|password|base-url|service-name)\s*:")
DOMAIN_SEMANTICS = re.compile(r"(?i)\b(?:ttl|timeout|expires?|amount|currency|timezone|pageSize|feature.?flag|lock|cache)\b")
TODO = re.compile(r"\b(?:TODO|FIXME)\b", re.IGNORECASE)
TODO_METADATA = re.compile(r"(?:owner\s*=.+).*(?:remove-when\s*=|expires\s*=)", re.IGNORECASE)
SUPPRESSION = re.compile(r"comment-governance-disable-next-line\s+(CG-[A-Z]\d{3})")
SUPPRESSION_METADATA = re.compile(r"reason=.+;\s*owner=.+;\s*(?:expires|remove-when)=.+", re.IGNORECASE)
SENSITIVE = re.compile(
    r"(?i)(?:password|passwd|secret|token|api[_-]?key)\s*[:=]\s*[\"']?(?!<|\$\{|example|dummy|test|redacted)[A-Za-z0-9_./+\-=]{8,}"
)
GENERATED_MARKERS = ("DO NOT EDIT", "DO NOT EDIT MANUALLY", "Generated by", "@generated")


@dataclass(frozen=True)
class Finding:
    rule_id: str
    severity: str
    path: str
    line: int
    message: str
    remediation: str

    @property
    def fingerprint(self) -> str:
        # 基线身份不能依赖行号，否则在文件头增加注释会把所有历史问题误判为新增。
        return f"{self.rule_id}:{self.path}:{self.message}"


def is_excluded(path: Path) -> bool:
    """排除构建、依赖、生成和归档目录，避免把不可维护文件计入债务。"""
    return bool(set(path.parts) & EXCLUDED_PARTS)


def is_generated(text: str) -> bool:
    """生成声明必须位于文件头；普通正文中的同名文本不能绕过检查。"""
    header = "\n".join(text.splitlines()[:12])
    return any(marker.lower() in header.lower() for marker in GENERATED_MARKERS)


def scan_common(path: Path, relative: str, text: str) -> list[Finding]:
    findings: list[Finding] = []
    lines = text.splitlines()
    if path.suffix == ".py":
        try:
            candidates = {
                token.start[0]: token.string
                for token in tokenize.generate_tokens(StringIO(text).readline)
                if token.type == tokenize.COMMENT
            }
        except tokenize.TokenError:
            candidates = {}
    else:
        candidates = {index: line for index, line in enumerate(lines, start=1)}
    for index, line in candidates.items():
        if TODO.search(line) and not TODO_METADATA.search(line):
            findings.append(Finding(
                "CG-P003", "PROHIBITED", relative, index,
                "TODO/FIXME 缺少负责人和移除条件",
                "使用 TODO(task, owner=team, remove-when=condition) 或 expires=YYYY-MM-DD",
            ))
        if SENSITIVE.search(line) and not line.lstrip().startswith(("# example", "// example")):
            findings.append(Finding(
                "CG-P001", "PROHIBITED", relative, index,
                "疑似在源码或注释中包含真实敏感值",
                "删除敏感值并使用 <REDACTED>、${ENV_NAME} 或明确的 synthetic placeholder",
            ))
        if COMMENTED_CODE.search(line):
            findings.append(Finding(
                "CG-P002", "PROHIBITED", relative, index,
                "发现疑似被注释掉的代码",
                "删除失效实现；需要恢复时通过 Git 历史检索",
            ))
        if AUTHOR_HISTORY.search(line):
            findings.append(Finding(
                "CG-P002", "PROHIBITED", relative, index,
                "注释记录了个人作者或修改历史",
                "删除个人历史；保留业务决策原因，变更记录交由 Git 管理",
            ))
        if RESTATEMENT.search(line):
            findings.append(Finding(
                "CG-P004", "PROHIBITED", relative, index,
                "注释仅复述代码动作，没有表达意图或不变量",
                "删除该注释，或改写为业务原因、约束和失败策略",
            ))
        match = SUPPRESSION.search(line)
        if match:
            metadata = lines[index] if index < len(lines) else ""
            if not SUPPRESSION_METADATA.search(metadata):
                findings.append(Finding(
                    "CG-B005", "BLOCKER", relative, index,
                    "注释治理豁免缺少原因、负责人或到期/移除条件",
                    "在下一行填写 reason=...; owner=负责人; expires=YYYY-MM-DD",
                ))
            else:
                expiry = re.search(r"expires=(\d{4}-\d{2}-\d{2})", metadata)
                if expiry and date.fromisoformat(expiry.group(1)) < date.today():
                    findings.append(Finding(
                        "CG-B005", "BLOCKER", relative, index,
                        "注释治理豁免已经过期",
                        "修复原问题或经负责人确认后更新有效期",
                    ))
    return findings


def has_leading_doc(lines: list[str], declaration_index: int, suffix: str) -> bool:
    cursor = declaration_index - 1
    while cursor >= 0 and (not lines[cursor].strip() or lines[cursor].lstrip().startswith("@")):
        cursor -= 1
    if cursor < 0:
        return False
    while cursor >= 0 and lines[cursor].lstrip().startswith("*"):
        cursor -= 1
    return cursor >= 0 and lines[cursor].lstrip().startswith("/**")


def scan_java(path: Path, relative: str, text: str) -> list[Finding]:
    findings: list[Finding] = []
    lines = text.splitlines()
    for index, line in enumerate(lines):
        declaration = PUBLIC_DECLARATION.search(line)
        if declaration and not has_leading_doc(lines, index, ".java"):
            findings.append(Finding(
                "CG-B001", "BLOCKER", relative, index + 1,
                f"公共 Java 类型 {declaration.group('name')} 缺少 Javadoc",
                "说明类型职责、调用边界及无法由类型系统表达的不变量",
            ))
    return findings


def scan_python(path: Path, relative: str, text: str) -> list[Finding]:
    findings: list[Finding] = []
    try:
        tree = ast.parse(text)
    except SyntaxError:
        return findings
    if ast.get_docstring(tree) is None:
        findings.append(Finding(
            "CG-B001", "BLOCKER", relative, 1,
            "Python 模块缺少模块级 docstring",
            "说明模块职责、边界和重要副作用",
        ))
    for node in tree.body:
        if isinstance(node, (ast.ClassDef, ast.FunctionDef, ast.AsyncFunctionDef)) and not node.name.startswith("_"):
            if ast.get_docstring(node) is None:
                findings.append(Finding(
                    "CG-B001", "BLOCKER", relative, node.lineno,
                    f"公共 Python 符号 {node.name} 缺少 docstring",
                    "使用 PEP 257 docstring 说明调用方需要的契约",
                ))
    return findings


def scan_typescript(relative: str, text: str) -> list[Finding]:
    """检查跨模块导出的前端契约；组件内部局部函数由评审清单判断语义价值。"""
    findings: list[Finding] = []
    lines = text.splitlines()
    for index, line in enumerate(lines):
        declaration = TS_PUBLIC_DECLARATION.search(line)
        if declaration and not has_leading_doc(lines, index, ".ts"):
            findings.append(Finding(
                "CG-B001", "BLOCKER", relative, index + 1,
                f"导出的 TypeScript/Vue 契约 {declaration.group('name')} 缺少 TSDoc/JSDoc",
                "说明跨模块职责、状态边界、异常及调用方不能自行推断的约束",
            ))
    return findings


def scan_sql(relative: str, text: str) -> list[Finding]:
    """有结构变更或数据写入的 SQL 必须提供目的和回滚说明。"""
    if not SQL_RISKY.search(text):
        return []
    findings: list[Finding] = []
    if not SQL_PURPOSE.search("\n".join(text.splitlines()[:20])):
        findings.append(Finding(
            "CG-B002", "BLOCKER", relative, 1,
            "SQL 迁移缺少目的说明",
            "在文件头添加 -- 目的：...，说明业务不变量和数据假设",
        ))
    if not SQL_ROLLBACK.search("\n".join(text.splitlines()[:20])):
        findings.append(Finding(
            "CG-B002", "BLOCKER", relative, 1,
            "SQL 迁移缺少回滚或不可逆影响说明",
            "在文件头添加 -- 回滚：...，说明恢复步骤或不可逆风险",
        ))
    return findings


def scan_config(relative: str, text: str) -> list[Finding]:
    """提示具有安全或部署影响的配置补充默认值、失败语义和重启要求。"""
    findings: list[Finding] = []
    lines = text.splitlines()
    for index, line in enumerate(lines):
        if CONFIG_RISK.search(line):
            previous = lines[index - 1].strip() if index > 0 else ""
            if not previous.startswith("#"):
                findings.append(Finding(
                    "CG-A003", "ADVISORY", relative, index + 1,
                    "非默认安全或部署配置缺少邻近说明",
                    "说明默认值、合法范围、失败影响以及修改后是否需要重启",
                ))
        if DOMAIN_SEMANTICS.search(line) and not line.lstrip().startswith("#"):
            previous = lines[index - 1].strip() if index > 0 else ""
            if not previous.startswith("#"):
                findings.append(Finding(
                    "CG-A003", "ADVISORY", relative, index + 1,
                    "配置中的时间、缓存或容量语义缺少说明",
                    "补充单位、范围、TTL/失效策略或生命周期",
                ))
    return findings


def scan_file(root: Path, path: Path) -> list[Finding]:
    relative = path.relative_to(root).as_posix()
    try:
        text = path.read_text(encoding="utf-8")
    except UnicodeDecodeError:
        return []
    if is_generated(text):
        return []
    findings = scan_common(path, relative, text)
    if path.suffix == ".java":
        findings.extend(scan_java(path, relative, text))
    elif path.suffix == ".py":
        findings.extend(scan_python(path, relative, text))
    elif path.suffix in {".ts", ".tsx", ".vue"}:
        findings.extend(scan_typescript(relative, text))
    elif path.suffix == ".sql":
        findings.extend(scan_sql(relative, text))
    elif path.suffix in {".yaml", ".yml"}:
        findings.extend(scan_config(relative, text))
    return findings


def git_changed_files(root: Path, base: str | None) -> set[str] | None:
    """有基线时检查差异；无 Git 上下文时返回 None，让本地执行退化为全量报告。"""
    command = ["git", "diff", "--name-only", "--diff-filter=ACMR"]
    if base:
        command.append(f"{base}...HEAD")
    try:
        result = subprocess.run(command, cwd=root, check=True, capture_output=True, text=True)
    except (OSError, subprocess.CalledProcessError):
        return None
    return {line.replace("\\", "/") for line in result.stdout.splitlines() if line.strip()}


def discover_files(root: Path, changed: set[str] | None) -> list[Path]:
    if changed is not None:
        candidates = [root / item for item in changed]
    else:
        candidates = []
        # 在进入目录前剪枝，避免 node_modules、构建产物和本地缓存拖慢全量扫描。
        for current, directories, files in os.walk(root):
            directories[:] = [name for name in directories if name not in EXCLUDED_PARTS]
            candidates.extend(Path(current) / name for name in files)
    return sorted(
        path for path in candidates
        if path.is_file() and path.suffix.lower() in SUPPORTED_SUFFIXES and not is_excluded(path.relative_to(root))
    )


def load_baseline(path: Path) -> set[str]:
    if not path.exists():
        return set()
    data = json.loads(path.read_text(encoding="utf-8"))
    return {item["fingerprint"] for item in data.get("findings", [])}


def remediation_metadata(path: str) -> tuple[str, str]:
    """按规范中的风险波次为债务分组；负责人字段使用稳定模块团队而非个人。"""
    wave_one_markers = (
        "service-auth/", "service-org/", "service-tenant/", "service-lowcode/",
        "platform-gateway/", "ai-llm-gateway/", "global-action", "temporal",
    )
    wave_two_markers = ("common-dto/", "controller/", "/api/", "/store/", "/registry/", "composable")
    wave = "wave-1" if any(item in path.lower() for item in wave_one_markers) else (
        "wave-2" if any(item in path.lower() for item in wave_two_markers) else "wave-3"
    )
    module = path.split("/", 1)[0]
    owner = {
        "trio-base-ai": "ai-team",
        "trio-base-common": "platform-team",
        "trio-base-data": "data-team",
        "trio-base-frontend": "frontend-team",
        "trio-base-platform": "platform-team",
        "trio-base-services": "service-team",
    }.get(module, "platform-team")
    return wave, owner


def write_report(path: Path, findings: list[Finding]) -> None:
    modules: dict[str, int] = {}
    for finding in findings:
        module = finding.path.split("/", 1)[0]
        modules[module] = modules.get(module, 0) + 1
    payload = {
        "schemaVersion": 1,
        "summary": {"total": len(findings), "modules": modules},
        "findings": [
            {
                **asdict(item),
                "fingerprint": item.fingerprint,
                "remediationWave": remediation_metadata(item.path)[0],
                "owner": remediation_metadata(item.path)[1],
            }
            for item in findings
        ],
    }
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")


def new_blocking_findings(findings: list[Finding], baseline: set[str]) -> list[Finding]:
    """只有不在历史基线中的 BLOCKER/PROHIBITED 才阻断当前变更。"""
    return [
        item for item in findings
        if item.severity in {"BLOCKER", "PROHIBITED"} and item.fingerprint not in baseline
    ]


def main() -> int:
    parser = argparse.ArgumentParser(description="TrioBase comment governance scanner")
    parser.add_argument("--root", type=Path, default=Path.cwd())
    parser.add_argument("--base", help="Git merge base/ref used for differential enforcement")
    parser.add_argument("--all", action="store_true", help="Scan every supported file")
    parser.add_argument("--baseline", type=Path, default=Path("cicd/comment-governance-baseline.json"))
    parser.add_argument("--report", type=Path, default=Path("build/comment-governance-report.json"))
    parser.add_argument("--write-baseline", action="store_true")
    args = parser.parse_args()

    root = args.root.resolve()
    changed = None if args.all or args.write_baseline else git_changed_files(root, args.base)
    findings = [finding for path in discover_files(root, changed) for finding in scan_file(root, path)]
    findings.sort(key=lambda item: (item.path, item.line, item.rule_id))

    report_path = args.report if args.report.is_absolute() else root / args.report
    write_report(report_path, findings)
    if args.write_baseline:
        baseline_path = args.baseline if args.baseline.is_absolute() else root / args.baseline
        write_report(baseline_path, findings)
        print(f"Wrote comment-governance baseline with {len(findings)} findings to {baseline_path}")
        return 0

    baseline_path = args.baseline if args.baseline.is_absolute() else root / args.baseline
    baseline = load_baseline(baseline_path)
    blocking = new_blocking_findings(findings, baseline)
    for item in findings:
        state = "NEW" if item.fingerprint not in baseline else "BASELINE"
        print(f"{state} {item.severity} {item.rule_id} {item.path}:{item.line} {item.message}")
    print(f"Comment governance: {len(findings)} findings, {len(blocking)} new blocking violations")
    return 1 if blocking else 0


if __name__ == "__main__":
    sys.exit(main())
