export interface LifecycleResourceConfig {
  actions: Array<{ label: string; method?: 'POST' | 'PUT'; path: string }>;
  assetType: string;
  createEndpoint: string;
  description: string;
  title: string;
  writePermission: string;
}

export const lifecycleResources: Record<string, LifecycleResourceConfig> = {
  applications: { actions:[{label:'提交审批',path:'/openapi/management/applications/{id}/submit'},{label:'激活',path:'/openapi/management/applications/{id}/activate'},{label:'暂停',path:'/openapi/management/applications/{id}/suspend'},{label:'重新激活',path:'/openapi/management/applications/{id}/reactivate'},{label:'撤销',path:'/openapi/management/applications/{id}/revoke'}], assetType: 'applications', createEndpoint: '/openapi/management/applications', description: '应用、环境客户端、凭证轮换与安全状态', title: '接入应用', writePermission: '/api/v1/openapi/management/applications:POST' },
  callbacks: { actions:[{label:'发布版本',path:'/openapi/management/callback-profiles/versions/{id}/publish'},{label:'弃用版本',path:'/openapi/management/callback-profiles/versions/{id}/deprecate'}], assetType: 'callbacks', createEndpoint: '/openapi/management/callback-profiles', description: '验签、关联、去重、应答与工作流 Signal', title: '回调配置', writePermission: '/api/v1/openapi/management/callback-profiles:POST' },
  connectors: { actions:[{label:'发布版本',path:'/openapi/management/connectors/versions/{id}/publish'},{label:'弃用版本',path:'/openapi/management/connectors/versions/{id}/deprecate'},{label:'归档',path:'/openapi/management/connectors/{id}/archive'}], assetType: 'connectors', createEndpoint: '/openapi/management/connectors', description: '受控端点、网络策略与凭证引用', title: '连接器', writePermission: '/api/v1/openapi/management/connectors:POST' },
  mappings: { actions:[{label:'发布版本',path:'/openapi/management/mappings/versions/{id}/publish'},{label:'预览转换',path:'/openapi/management/mappings/versions/{id}/preview'}], assetType: 'mappings', createEndpoint: '/openapi/management/mappings', description: '字段映射、转换预览与契约测试', title: '字段映射', writePermission: '/api/v1/openapi/management/mappings:POST' },
  orchestrations: { actions:[{label:'发布版本',path:'/openapi/management/orchestrations/versions/{id}/publish'},{label:'弃用版本',path:'/openapi/management/orchestrations/versions/{id}/deprecate'},{label:'归档',path:'/openapi/management/orchestrations/{id}/archive'}], assetType: 'orchestrations', createEndpoint: '/openapi/management/orchestrations', description: 'Temporal 多步骤编排、等待与补偿', title: '流程编排', writePermission: '/api/v1/openapi/management/orchestrations:POST' },
  policies: { actions:[{label:'发布策略版本',path:'/openapi/management/policies/{id}/publish'}], assetType: 'policies', createEndpoint: '/openapi/management/policies', description: '限流、配额、并发、安全策略与快照', title: '流控与安全策略', writePermission: '/api/v1/openapi/management/products:POST' },
  products: { actions:[{label:'发布产品版本',path:'/openapi/management/products/versions/{id}/publish'},{label:'弃用产品版本',path:'/openapi/management/products/versions/{id}/deprecate'},{label:'归档产品',path:'/openapi/management/products/{id}/archive'}], assetType: 'products', createEndpoint: '/openapi/management/products', description: '开放能力、版本、范围与默认策略', title: 'API 产品', writePermission: '/api/v1/openapi/management/products:POST' },
  routes: { actions:[{label:'发布路由版本',path:'/openapi/management/routes/versions/{id}/publish'},{label:'创建 Release',path:'/openapi/management/routes/versions/{id}/releases'},{label:'激活 Release',path:'/openapi/management/releases/{id}/activate'},{label:'回滚路由',path:'/openapi/management/routes/{id}/rollback'}], assetType: 'routes', createEndpoint: '/openapi/management/routes', description: '路由条件、不可变 Release、激活与回滚', title: '路由与发布', writePermission: '/api/v1/openapi/management/routes:POST' },
  structures: { actions:[{label:'发布版本',path:'/openapi/management/structures/versions/{id}/publish'},{label:'弃用版本',path:'/openapi/management/structures/versions/{id}/deprecate'},{label:'归档版本',path:'/openapi/management/structures/versions/{id}/archive'}], assetType: 'structures', createEndpoint: '/openapi/management/structures', description: '标准/外部结构、版本、兼容性与导入导出', title: '标准与外部结构', writePermission: '/api/v1/openapi/management/structures:POST' },
  subscriptions: { actions:[{label:'激活订阅',path:'/openapi/management/subscriptions/{id}/activate'},{label:'升级订阅',path:'/openapi/management/subscriptions/{id}/upgrade'},{label:'暂停订阅',path:'/openapi/management/subscriptions/{id}/suspend'},{label:'撤销订阅',path:'/openapi/management/subscriptions/{id}/revoke'}], assetType: 'subscriptions', createEndpoint: '/openapi/management/subscriptions', description: '产品订阅、版本升级、暂停撤销与双重审批', title: '订阅与审批', writePermission: '/api/v1/openapi/management/applications:POST' },
  'value-maps': { actions:[{label:'发布版本',path:'/openapi/management/value-maps/versions/{id}/publish'},{label:'值查找',path:'/openapi/management/value-maps/versions/{id}/lookup'}], assetType: 'value-maps', createEndpoint: '/openapi/management/value-maps', description: '正反向枚举映射、默认值与未命中策略', title: '值映射', writePermission: '/api/v1/openapi/management/mappings:POST' },
};
