-- Platform operations permissions and menus.
-- Search, refresh, pagination, and detail views reuse page-level GET permissions.

INSERT INTO sys_permission(id, resource, action, description) VALUES
    ('P037', '/api/v1/announcements', 'GET', '查看通知公告'),
    ('P038', '/api/v1/announcements', 'POST', '新增通知公告'),
    ('P039', '/api/v1/announcements/*', 'PUT', '修改通知公告'),
    ('P040', '/api/v1/announcements/*', 'DELETE', '删除通知公告'),
    ('P041', '/api/v1/announcements/*/publish', 'POST', '发布通知公告'),
    ('P042', '/api/v1/announcements/*/unpublish', 'POST', '下线通知公告'),
    ('P043', '/api/v1/messages', 'GET', '查看站内消息管理'),
    ('P044', '/api/v1/messages', 'POST', '发送站内消息'),
    ('P045', '/api/v1/messages/*', 'DELETE', '删除站内消息'),
    ('P046', '/api/v1/files', 'GET', '查看文件中心'),
    ('P047', '/api/v1/files', 'POST', '上传文件'),
    ('P048', '/api/v1/files/*', 'GET', '下载文件'),
    ('P049', '/api/v1/files/*', 'PUT', '启停文件'),
    ('P050', '/api/v1/files/*', 'DELETE', '删除文件'),
    ('P051', '/api/v1/file-references', 'GET', '查看文件业务引用'),
    ('P052', '/api/v1/file-references', 'POST', '绑定文件业务引用'),
    ('P053', '/api/v1/import-export-tasks', 'GET', '查看导入导出任务'),
    ('P054', '/api/v1/import-export-tasks/import', 'POST', '创建导入任务'),
    ('P055', '/api/v1/import-export-tasks/export', 'POST', '创建导出任务'),
    ('P056', '/api/v1/import-export-tasks/*/cancel', 'POST', '取消导入导出任务'),
    ('P057', '/api/v1/import-export-tasks/*/result', 'GET', '下载导入导出结果'),
    ('P058', '/api/v1/jobs', 'GET', '查看后台任务'),
    ('P059', '/api/v1/jobs', 'POST', '新增后台任务'),
    ('P060', '/api/v1/jobs/*', 'PUT', '修改后台任务'),
    ('P061', '/api/v1/jobs/*', 'DELETE', '删除后台任务'),
    ('P062', '/api/v1/jobs/*/trigger', 'POST', '手动触发后台任务'),
    ('P063', '/api/v1/jobs/*/logs', 'GET', '查看后台任务执行日志'),
    ('P064', '/api/v1/import-export-tasks/*', 'PUT', '更新导入导出任务进度')
ON CONFLICT (id) DO UPDATE SET
    resource = EXCLUDED.resource,
    action = EXCLUDED.action,
    description = EXCLUDED.description,
    updated_by = 'SYSTEM',
    updated_at = CURRENT_TIMESTAMP;

INSERT INTO sys_menu (
    id, parent_id, menu_key, menu_name, path, component, icon, active_icon, active_path,
    menu_type, menu_group, sort_order, visible, status, keep_alive, affix_tab,
    hide_in_menu, hide_children_in_menu, hide_in_breadcrumb, hide_in_tab,
    badge, badge_type, badge_variant, permission_id, permission_code, description
) VALUES
    ('M015', NULL, 'Operations', '运营支撑', '/operations', NULL,
     'mdi:application-cog-outline', NULL, NULL,
     'catalog', 'operations', 90, 1, 1, 0, 0, 0, 0, 0, 0,
     NULL, NULL, NULL, NULL, NULL, '平台运营支撑能力'),
    ('M016', 'M015', 'OperationsAnnouncement', '通知公告', '/operations/announcement', '/operations/announcement/list',
     'mdi:bullhorn-outline', NULL, NULL,
     'menu', 'operations', 10, 1, 1, 0, 0, 0, 0, 0, 0,
     NULL, NULL, NULL, 'P037', '/api/v1/announcements:GET', '通知公告管理'),
    ('M016_BTN_CREATE', 'M016', 'OperationsAnnouncementCreate', '新增', NULL, NULL, NULL, NULL, NULL,
     'button', 'operations', 10, 1, 1, 0, 0, 1, 0, 0, 0,
     NULL, NULL, NULL, 'P038', '/api/v1/announcements:POST', '通知公告-新增'),
    ('M016_BTN_EDIT', 'M016', 'OperationsAnnouncementEdit', '修改', NULL, NULL, NULL, NULL, NULL,
     'button', 'operations', 20, 1, 1, 0, 0, 1, 0, 0, 0,
     NULL, NULL, NULL, 'P039', '/api/v1/announcements/*:PUT', '通知公告-修改'),
    ('M016_BTN_DELETE', 'M016', 'OperationsAnnouncementDelete', '删除', NULL, NULL, NULL, NULL, NULL,
     'button', 'operations', 30, 1, 1, 0, 0, 1, 0, 0, 0,
     NULL, NULL, NULL, 'P040', '/api/v1/announcements/*:DELETE', '通知公告-删除'),
    ('M016_BTN_PUBLISH', 'M016', 'OperationsAnnouncementPublish', '发布', NULL, NULL, NULL, NULL, NULL,
     'button', 'operations', 40, 1, 1, 0, 0, 1, 0, 0, 0,
     NULL, NULL, NULL, 'P041', '/api/v1/announcements/*/publish:POST', '通知公告-发布'),
    ('M016_BTN_UNPUBLISH', 'M016', 'OperationsAnnouncementUnpublish', '下线', NULL, NULL, NULL, NULL, NULL,
     'button', 'operations', 50, 1, 1, 0, 0, 1, 0, 0, 0,
     NULL, NULL, NULL, 'P042', '/api/v1/announcements/*/unpublish:POST', '通知公告-下线'),
    ('M017', 'M015', 'OperationsMessage', '站内消息', '/operations/message', '/operations/message/list',
     'mdi:message-badge-outline', NULL, NULL,
     'menu', 'operations', 20, 1, 1, 0, 0, 0, 0, 0, 0,
     NULL, NULL, NULL, 'P043', '/api/v1/messages:GET', '站内消息管理'),
    ('M017_BTN_SEND', 'M017', 'OperationsMessageSend', '发送', NULL, NULL, NULL, NULL, NULL,
     'button', 'operations', 10, 1, 1, 0, 0, 1, 0, 0, 0,
     NULL, NULL, NULL, 'P044', '/api/v1/messages:POST', '站内消息-发送'),
    ('M017_BTN_DELETE', 'M017', 'OperationsMessageDelete', '删除', NULL, NULL, NULL, NULL, NULL,
     'button', 'operations', 20, 1, 1, 0, 0, 1, 0, 0, 0,
     NULL, NULL, NULL, 'P045', '/api/v1/messages/*:DELETE', '站内消息-删除'),
    ('M018', 'M015', 'OperationsFile', '文件中心', '/operations/file', '/operations/file/list',
     'mdi:file-cog-outline', NULL, NULL,
     'menu', 'operations', 30, 1, 1, 0, 0, 0, 0, 0, 0,
     NULL, NULL, NULL, 'P046', '/api/v1/files:GET', '文件中心管理'),
    ('M018_BTN_UPLOAD', 'M018', 'OperationsFileUpload', '上传', NULL, NULL, NULL, NULL, NULL,
     'button', 'operations', 10, 1, 1, 0, 0, 1, 0, 0, 0,
     NULL, NULL, NULL, 'P047', '/api/v1/files:POST', '文件中心-上传'),
    ('M018_BTN_DOWNLOAD', 'M018', 'OperationsFileDownload', '下载', NULL, NULL, NULL, NULL, NULL,
     'button', 'operations', 20, 1, 1, 0, 0, 1, 0, 0, 0,
     NULL, NULL, NULL, 'P048', '/api/v1/files/*:GET', '文件中心-下载'),
    ('M018_BTN_EDIT', 'M018', 'OperationsFileEdit', '启停', NULL, NULL, NULL, NULL, NULL,
     'button', 'operations', 30, 1, 1, 0, 0, 1, 0, 0, 0,
     NULL, NULL, NULL, 'P049', '/api/v1/files/*:PUT', '文件中心-启停'),
    ('M018_BTN_DELETE', 'M018', 'OperationsFileDelete', '删除', NULL, NULL, NULL, NULL, NULL,
     'button', 'operations', 40, 1, 1, 0, 0, 1, 0, 0, 0,
     NULL, NULL, NULL, 'P050', '/api/v1/files/*:DELETE', '文件中心-删除'),
    ('M018_BTN_REF_VIEW', 'M018', 'OperationsFileReferenceView', '查看引用', NULL, NULL, NULL, NULL, NULL,
     'button', 'operations', 50, 1, 1, 0, 0, 1, 0, 0, 0,
     NULL, NULL, NULL, 'P051', '/api/v1/file-references:GET', '文件中心-查看业务引用'),
    ('M018_BTN_REF', 'M018', 'OperationsFileReference', '绑定引用', NULL, NULL, NULL, NULL, NULL,
     'button', 'operations', 60, 1, 1, 0, 0, 1, 0, 0, 0,
     NULL, NULL, NULL, 'P052', '/api/v1/file-references:POST', '文件中心-绑定业务引用'),
    ('M019', 'M015', 'OperationsImportExport', '导入导出', '/operations/import-export', '/operations/import-export/list',
     'mdi:database-arrow-up-outline', NULL, NULL,
     'menu', 'operations', 40, 1, 1, 0, 0, 0, 0, 0, 0,
     NULL, NULL, NULL, 'P053', '/api/v1/import-export-tasks:GET', '导入导出任务管理'),
    ('M019_BTN_IMPORT', 'M019', 'OperationsImportTask', '导入', NULL, NULL, NULL, NULL, NULL,
     'button', 'operations', 10, 1, 1, 0, 0, 1, 0, 0, 0,
     NULL, NULL, NULL, 'P054', '/api/v1/import-export-tasks/import:POST', '导入导出-创建导入任务'),
    ('M019_BTN_EXPORT', 'M019', 'OperationsExportTask', '导出', NULL, NULL, NULL, NULL, NULL,
     'button', 'operations', 20, 1, 1, 0, 0, 1, 0, 0, 0,
     NULL, NULL, NULL, 'P055', '/api/v1/import-export-tasks/export:POST', '导入导出-创建导出任务'),
    ('M019_BTN_CANCEL', 'M019', 'OperationsTaskCancel', '取消', NULL, NULL, NULL, NULL, NULL,
     'button', 'operations', 30, 1, 1, 0, 0, 1, 0, 0, 0,
     NULL, NULL, NULL, 'P056', '/api/v1/import-export-tasks/*/cancel:POST', '导入导出-取消任务'),
    ('M019_BTN_DOWNLOAD', 'M019', 'OperationsTaskDownload', '下载结果', NULL, NULL, NULL, NULL, NULL,
     'button', 'operations', 40, 1, 1, 0, 0, 1, 0, 0, 0,
     NULL, NULL, NULL, 'P057', '/api/v1/import-export-tasks/*/result:GET', '导入导出-下载结果'),
    ('M019_API_UPDATE', 'M019', 'OperationsTaskUpdateApi', '更新任务(API)', NULL, NULL, NULL, NULL, NULL,
     'button', 'operations', 90, 0, 1, 0, 0, 1, 0, 0, 0,
     NULL, NULL, NULL, 'P064', '/api/v1/import-export-tasks/*:PUT', '导入导出-更新任务进度'),
    ('M020', 'M015', 'OperationsJob', '后台任务', '/operations/job', '/operations/job/list',
     'mdi:timer-cog-outline', NULL, NULL,
     'menu', 'operations', 50, 1, 1, 0, 0, 0, 0, 0, 0,
     NULL, NULL, NULL, 'P058', '/api/v1/jobs:GET', '后台任务调度管理'),
    ('M020_BTN_CREATE', 'M020', 'OperationsJobCreate', '新增', NULL, NULL, NULL, NULL, NULL,
     'button', 'operations', 10, 1, 1, 0, 0, 1, 0, 0, 0,
     NULL, NULL, NULL, 'P059', '/api/v1/jobs:POST', '后台任务-新增'),
    ('M020_BTN_EDIT', 'M020', 'OperationsJobEdit', '修改', NULL, NULL, NULL, NULL, NULL,
     'button', 'operations', 20, 1, 1, 0, 0, 1, 0, 0, 0,
     NULL, NULL, NULL, 'P060', '/api/v1/jobs/*:PUT', '后台任务-修改启停'),
    ('M020_BTN_DELETE', 'M020', 'OperationsJobDelete', '删除', NULL, NULL, NULL, NULL, NULL,
     'button', 'operations', 30, 1, 1, 0, 0, 1, 0, 0, 0,
     NULL, NULL, NULL, 'P061', '/api/v1/jobs/*:DELETE', '后台任务-删除'),
    ('M020_BTN_TRIGGER', 'M020', 'OperationsJobTrigger', '触发', NULL, NULL, NULL, NULL, NULL,
     'button', 'operations', 40, 1, 1, 0, 0, 1, 0, 0, 0,
     NULL, NULL, NULL, 'P062', '/api/v1/jobs/*/trigger:POST', '后台任务-手动触发'),
    ('M020_BTN_LOGS', 'M020', 'OperationsJobLogs', '执行日志', NULL, NULL, NULL, NULL, NULL,
     'button', 'operations', 50, 1, 1, 0, 0, 1, 0, 0, 0,
     NULL, NULL, NULL, 'P063', '/api/v1/jobs/*/logs:GET', '后台任务-执行日志')
ON CONFLICT (id) DO UPDATE SET
    parent_id = EXCLUDED.parent_id,
    menu_key = EXCLUDED.menu_key,
    menu_name = EXCLUDED.menu_name,
    path = EXCLUDED.path,
    component = EXCLUDED.component,
    icon = EXCLUDED.icon,
    active_icon = EXCLUDED.active_icon,
    active_path = EXCLUDED.active_path,
    menu_type = EXCLUDED.menu_type,
    menu_group = EXCLUDED.menu_group,
    sort_order = EXCLUDED.sort_order,
    visible = EXCLUDED.visible,
    status = EXCLUDED.status,
    keep_alive = EXCLUDED.keep_alive,
    affix_tab = EXCLUDED.affix_tab,
    hide_in_menu = EXCLUDED.hide_in_menu,
    hide_children_in_menu = EXCLUDED.hide_children_in_menu,
    hide_in_breadcrumb = EXCLUDED.hide_in_breadcrumb,
    hide_in_tab = EXCLUDED.hide_in_tab,
    badge = EXCLUDED.badge,
    badge_type = EXCLUDED.badge_type,
    badge_variant = EXCLUDED.badge_variant,
    permission_id = EXCLUDED.permission_id,
    permission_code = EXCLUDED.permission_code,
    description = EXCLUDED.description,
    updated_by = 'SYSTEM',
    updated_at = CURRENT_TIMESTAMP;

INSERT INTO sys_role_menu(id, role_id, menu_id, created_by, updated_by)
SELECT '01' || upper(substr(md5('R001' || ':' || m.id), 1, 24)),
       'R001',
       m.id,
       'SYSTEM',
       'SYSTEM'
FROM sys_menu m
WHERE m.id IN (
    'M015',
    'M016',
    'M016_BTN_CREATE',
    'M016_BTN_EDIT',
    'M016_BTN_DELETE',
    'M016_BTN_PUBLISH',
    'M016_BTN_UNPUBLISH',
    'M017',
    'M017_BTN_SEND',
    'M017_BTN_DELETE',
    'M018',
    'M018_BTN_UPLOAD',
    'M018_BTN_DOWNLOAD',
    'M018_BTN_EDIT',
    'M018_BTN_DELETE',
    'M018_BTN_REF_VIEW',
    'M018_BTN_REF',
    'M019',
    'M019_BTN_IMPORT',
    'M019_BTN_EXPORT',
    'M019_BTN_CANCEL',
    'M019_BTN_DOWNLOAD',
    'M019_API_UPDATE',
    'M020',
    'M020_BTN_CREATE',
    'M020_BTN_EDIT',
    'M020_BTN_DELETE',
    'M020_BTN_TRIGGER',
    'M020_BTN_LOGS'
)
ON CONFLICT (role_id, menu_id) DO NOTHING;
