ALTER TABLE sys_menu ADD COLUMN IF NOT EXISTS component VARCHAR(256);
ALTER TABLE sys_menu ADD COLUMN IF NOT EXISTS active_icon VARCHAR(64);
ALTER TABLE sys_menu ADD COLUMN IF NOT EXISTS active_path VARCHAR(256);
ALTER TABLE sys_menu ADD COLUMN IF NOT EXISTS menu_type VARCHAR(32) NOT NULL DEFAULT 'menu';
ALTER TABLE sys_menu ADD COLUMN IF NOT EXISTS status SMALLINT NOT NULL DEFAULT 1;
ALTER TABLE sys_menu ADD COLUMN IF NOT EXISTS keep_alive SMALLINT NOT NULL DEFAULT 0;
ALTER TABLE sys_menu ADD COLUMN IF NOT EXISTS affix_tab SMALLINT NOT NULL DEFAULT 0;
ALTER TABLE sys_menu ADD COLUMN IF NOT EXISTS hide_in_menu SMALLINT NOT NULL DEFAULT 0;
ALTER TABLE sys_menu ADD COLUMN IF NOT EXISTS hide_children_in_menu SMALLINT NOT NULL DEFAULT 0;
ALTER TABLE sys_menu ADD COLUMN IF NOT EXISTS hide_in_breadcrumb SMALLINT NOT NULL DEFAULT 0;
ALTER TABLE sys_menu ADD COLUMN IF NOT EXISTS hide_in_tab SMALLINT NOT NULL DEFAULT 0;
ALTER TABLE sys_menu ADD COLUMN IF NOT EXISTS badge VARCHAR(64);
ALTER TABLE sys_menu ADD COLUMN IF NOT EXISTS badge_type VARCHAR(32);
ALTER TABLE sys_menu ADD COLUMN IF NOT EXISTS badge_variant VARCHAR(32);
ALTER TABLE sys_menu ADD COLUMN IF NOT EXISTS permission_code VARCHAR(128);
ALTER TABLE sys_menu ALTER COLUMN path DROP NOT NULL;

UPDATE sys_menu
SET status = visible
WHERE status IS NULL;

UPDATE sys_menu
SET menu_type = CASE
    WHEN path IS NULL OR path = '' THEN 'button'
    WHEN parent_id IS NULL AND path NOT LIKE '/%' THEN 'catalog'
    ELSE 'menu'
END
WHERE menu_type IS NULL OR menu_type = '';
