INSERT INTO sys_menu (
    id, parent_id, menu_key, menu_name, path, component, icon, active_icon, active_path,
    menu_type, menu_group, sort_order, visible, status, keep_alive, affix_tab,
    hide_in_menu, hide_children_in_menu, hide_in_breadcrumb, hide_in_tab,
    badge, badge_type, badge_variant, permission_id, permission_code, description
) VALUES
    ('M001', NULL, 'dashboard', '仪表盘', '/dashboard', NULL, 'lucide:layout-dashboard', NULL, NULL,
     'catalog', 'general', 10, 1, 1, 0, 0, 0, 0, 0, 0,
     NULL, NULL, NULL, NULL, NULL, '工作台与分析概览'),
    ('M002', 'M001', 'analytics', '分析页', '/dashboard/analytics', '/dashboard/analytics/index', 'lucide:area-chart', NULL, NULL,
     'menu', 'general', 20, 1, 1, 0, 1, 0, 0, 0, 0,
     NULL, NULL, NULL, NULL, NULL, '经营指标与趋势分析'),
    ('M003', 'M001', 'workspace', '工作台', '/dashboard/workspace', '/dashboard/workspace/index', 'carbon:workspace', NULL, NULL,
     'menu', 'general', 30, 1, 1, 0, 0, 0, 0, 0, 0,
     NULL, NULL, NULL, NULL, NULL, '个人工作台'),
    ('M004', 'M008', 'users', '用户管理', '/system/user', '/system/user/list', 'mdi:user', NULL, NULL,
     'menu', 'system', 20, 1, 1, 0, 0, 0, 0, 0, 0,
     NULL, NULL, NULL, 'P001', '/api/v1/users:GET', '用户状态与角色分配'),
    ('M005', 'M008', 'roles', '角色管理', '/system/role', '/system/role/list', 'mdi:account-group', NULL, NULL,
     'menu', 'system', 30, 1, 1, 0, 0, 0, 0, 0, 0,
     NULL, NULL, NULL, 'P005', '/api/v1/roles:GET', '角色与权限绑定'),
    ('M006', 'M008', 'menus', '菜单管理', '/system/menu', '/system/menu/list', 'mdi:menu', NULL, NULL,
     'menu', 'system', 40, 1, 1, 0, 0, 0, 0, 0, 0,
     NULL, NULL, NULL, 'P013', '/api/v1/menus:GET', '后台菜单目录管理'),
    ('M007', NULL, 'permissions', '授权管理', '/admin/permissions', NULL, 'KeySquare', NULL, NULL,
     'menu', 'system', 90, 0, 0, 0, 0, 1, 0, 0, 0,
     NULL, NULL, NULL, 'P016', '/api/v1/permissions:GET', '保留菜单：前端页面尚未接入'),
    ('M008', NULL, 'system', '系统管理', '/system', NULL, 'ion:settings-outline', NULL, NULL,
     'catalog', 'system', 80, 1, 1, 0, 0, 0, 0, 0, 0,
     NULL, NULL, NULL, NULL, NULL, '系统基础配置'),
    ('M009', 'M008', 'dept', '部门管理', '/system/dept', '/system/dept/list', 'charm:organisation', NULL, NULL,
     'menu', 'system', 50, 1, 1, 0, 0, 0, 0, 0, 0,
     NULL, NULL, NULL, NULL, NULL, '组织与部门维护')
ON CONFLICT (id) DO UPDATE SET
    parent_id = EXCLUDED.parent_id,
    menu_key = EXCLUDED.menu_key,
    menu_name = EXCLUDED.menu_name,
    path = EXCLUDED.path,
    component = EXCLUDED.component,
    icon = EXCLUDED.icon,
    active_icon = EXCLUDED.active_icon,
    active_path = EXCLUDED.active_path,
    menu_type = EXCLUDED.menu_type,
    menu_group = EXCLUDED.menu_group,
    sort_order = EXCLUDED.sort_order,
    visible = EXCLUDED.visible,
    status = EXCLUDED.status,
    keep_alive = EXCLUDED.keep_alive,
    affix_tab = EXCLUDED.affix_tab,
    hide_in_menu = EXCLUDED.hide_in_menu,
    hide_children_in_menu = EXCLUDED.hide_children_in_menu,
    hide_in_breadcrumb = EXCLUDED.hide_in_breadcrumb,
    hide_in_tab = EXCLUDED.hide_in_tab,
    badge = EXCLUDED.badge,
    badge_type = EXCLUDED.badge_type,
    badge_variant = EXCLUDED.badge_variant,
    permission_id = EXCLUDED.permission_id,
    permission_code = EXCLUDED.permission_code,
    description = EXCLUDED.description;
