INSERT INTO sys_menu (
    id, parent_id, menu_key, menu_name, path, component, icon, active_icon, active_path,
    menu_type, menu_group, sort_order, visible, status, keep_alive, affix_tab,
    hide_in_menu, hide_children_in_menu, hide_in_breadcrumb, hide_in_tab,
    badge, badge_type, badge_variant, permission_id, permission_code, description
) VALUES
    ('01HK153X100000000000000010', 'M006', 'SystemMenuCreate', '新增', NULL, NULL, NULL, NULL, NULL,
     'button', 'system', 10, 1, 1, 0, 0,
     1, 0, 0, 0,
     NULL, NULL, NULL, NULL, 'System:Menu:Create', '菜单管理-新增按钮'),
    ('01HK153X110000000000000011', 'M006', 'SystemMenuEdit', '修改', NULL, NULL, NULL, NULL, NULL,
     'button', 'system', 20, 1, 1, 0, 0,
     1, 0, 0, 0,
     NULL, NULL, NULL, NULL, 'System:Menu:Edit', '菜单管理-修改按钮'),
    ('01HK153X120000000000000012', 'M006', 'SystemMenuDelete', '删除', NULL, NULL, NULL, NULL, NULL,
     'button', 'system', 30, 1, 1, 0, 0,
     1, 0, 0, 0,
     NULL, NULL, NULL, NULL, 'System:Menu:Delete', '菜单管理-删除按钮')
ON CONFLICT (id) DO UPDATE SET
    parent_id = EXCLUDED.parent_id,
    menu_key = EXCLUDED.menu_key,
    menu_name = EXCLUDED.menu_name,
    path = EXCLUDED.path,
    component = EXCLUDED.component,
    icon = EXCLUDED.icon,
    active_icon = EXCLUDED.active_icon,
    active_path = EXCLUDED.active_path,
    menu_type = EXCLUDED.menu_type,
    menu_group = EXCLUDED.menu_group,
    sort_order = EXCLUDED.sort_order,
    visible = EXCLUDED.visible,
    status = EXCLUDED.status,
    keep_alive = EXCLUDED.keep_alive,
    affix_tab = EXCLUDED.affix_tab,
    hide_in_menu = EXCLUDED.hide_in_menu,
    hide_children_in_menu = EXCLUDED.hide_children_in_menu,
    hide_in_breadcrumb = EXCLUDED.hide_in_breadcrumb,
    hide_in_tab = EXCLUDED.hide_in_tab,
    badge = EXCLUDED.badge,
    badge_type = EXCLUDED.badge_type,
    badge_variant = EXCLUDED.badge_variant,
    permission_id = EXCLUDED.permission_id,
    permission_code = EXCLUDED.permission_code,
    description = EXCLUDED.description;
