package com.triobase.platform.gateway.filter;
import com.sun.net.httpserver.HttpServer;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.Test;
import org.springframework.http.HttpMethod;
import org.springframework.mock.http.server.reactive.MockServerHttpRequest;
import org.springframework.mock.web.server.MockServerWebExchange;
import org.springframework.web.reactive.function.client.WebClient;
import java.net.InetSocketAddress;
import java.nio.charset.StandardCharsets;
import java.util.concurrent.atomic.AtomicBoolean;
import java.util.concurrent.atomic.AtomicReference;
import static org.assertj.core.api.Assertions.assertThat;
class OpenApiApplicationAdmissionFilterTest {
 private HttpServer server;
 @AfterEach void stop(){if(server!=null)server.stop(0);}
 @Test void disabledRuntimePassesThrough(){OpenApiApplicationAdmissionFilter filter=new OpenApiApplicationAdmissionFilter(WebClient.builder(),"http://127.0.0.1:1",false);var exchange=MockServerWebExchange.from(MockServerHttpRequest.get("/api/v1/openapi/runtime/orders.get").build());AtomicBoolean called=new AtomicBoolean();filter.filter(exchange,e->{called.set(true);return reactor.core.publisher.Mono.empty();}).block();assertThat(called).isTrue();}
 @Test void rejectsChunkedStateChangingRequestBeforeAdmission(){OpenApiApplicationAdmissionFilter filter=new OpenApiApplicationAdmissionFilter(WebClient.builder(),"http://127.0.0.1:1",true);var exchange=MockServerWebExchange.from(MockServerHttpRequest.method(HttpMethod.POST,"/api/v1/openapi/runtime/orders.submit").build());filter.filter(exchange,e->reactor.core.publisher.Mono.empty()).block();assertThat(exchange.getResponse().getStatusCode().value()).isEqualTo(411);}
 @Test void propagatesStandardRetryAfterForRateLimitDecision()throws Exception{server=HttpServer.create(new InetSocketAddress("127.0.0.1",0),0);server.createContext("/api/v1/openapi/internal/admission",e->{byte[] body="{\"code\":0,\"message\":\"success\",\"data\":{\"allowed\":false,\"httpStatus\":429,\"reason\":\"RATE_LIMITED\",\"policyVersion\":0,\"retryAfterSeconds\":7,\"maxBodyBytes\":0,\"maxConcurrency\":0,\"maxActiveWorkflows\":0}}".getBytes(StandardCharsets.UTF_8);e.getResponseHeaders().add("Content-Type","application/json");e.sendResponseHeaders(200,body.length);e.getResponseBody().write(body);e.close();});server.start();OpenApiApplicationAdmissionFilter filter=new OpenApiApplicationAdmissionFilter(WebClient.builder(),"http://127.0.0.1:"+server.getAddress().getPort(),true);var request=MockServerHttpRequest.get("/api/v1/openapi/runtime/orders.get").header("X-Tenant-Id","tenant-a").header("X-Client-Key","client-1").header("X-Environment","PROD").header("X-Client-Credential","secret").remoteAddress(new InetSocketAddress("127.0.0.1",12345)).build();var exchange=MockServerWebExchange.from(request);filter.filter(exchange,e->reactor.core.publisher.Mono.empty()).block();assertThat(exchange.getResponse().getStatusCode().value()).isEqualTo(429);assertThat(exchange.getResponse().getHeaders().getFirst("Retry-After")).isEqualTo("7");}
 @Test void marksCallbackAdmissionAndPropagatesTrustedGatewayContext()throws Exception{AtomicReference<String> admission=new AtomicReference<>();server=HttpServer.create(new InetSocketAddress("127.0.0.1",0),0);server.createContext("/api/v1/openapi/internal/admission",e->{admission.set(new String(e.getRequestBody().readAllBytes(),StandardCharsets.UTF_8));byte[] body="{\"code\":0,\"message\":\"success\",\"data\":{\"allowed\":true,\"httpStatus\":200,\"reason\":\"ALLOWED\",\"tenantId\":\"tenant-a\",\"applicationClientId\":\"client-1\",\"subscriptionId\":\"CALLBACK:v1\",\"policyVersion\":7,\"retryAfterSeconds\":0,\"maxBodyBytes\":1024,\"maxConcurrency\":10,\"maxActiveWorkflows\":5}}".getBytes(StandardCharsets.UTF_8);e.getResponseHeaders().add("Content-Type","application/json");e.sendResponseHeaders(200,body.length);e.getResponseBody().write(body);e.close();});server.start();OpenApiApplicationAdmissionFilter filter=new OpenApiApplicationAdmissionFilter(WebClient.builder(),"http://127.0.0.1:"+server.getAddress().getPort(),true);var request=MockServerHttpRequest.post("/api/v1/openapi/callbacks/cb_key").header("X-Tenant-Id","tenant-a").header("X-Client-Key","client-key").header("X-Environment","PROD").header("Content-Type","application/json").header("Content-Length","2").body("{}");var exchange=MockServerWebExchange.from(request);AtomicReference<String> trusted=new AtomicReference<>();filter.filter(exchange,e->{trusted.set(e.getRequest().getHeaders().getFirst("X-Gateway-Authenticated"));return reactor.core.publisher.Mono.empty();}).block();assertThat(admission.get()).contains("\"callback\":true").contains("\"routeKey\":\"cb_key\"");assertThat(trusted.get()).isEqualTo("true");}
}
