package com.triobase.service.openapi.service;
import com.baomidou.mybatisplus.core.conditions.query.LambdaQueryWrapper;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.node.JsonNodeFactory;
import com.triobase.common.core.context.SecurityContextHolder;
import com.triobase.common.core.exception.BizException;
import com.triobase.common.core.id.UlidGenerator;
import com.triobase.service.openapi.domain.entity.ApplicationClient;
import com.triobase.service.openapi.domain.entity.ApplicationContact;
import com.triobase.service.openapi.domain.entity.ApplicationOwner;
import com.triobase.service.openapi.domain.entity.IntegrationApplication;
import com.triobase.service.openapi.domain.enums.ApplicationLifecycleState;
import com.triobase.service.openapi.domain.enums.Environment;
import com.triobase.service.openapi.domain.enums.RiskLevel;
import com.triobase.service.openapi.dto.ApplicationClientResponse;
import com.triobase.service.openapi.dto.ApplicationResponse;
import com.triobase.service.openapi.dto.CreateApplicationClientRequest;
import com.triobase.service.openapi.dto.CreateApplicationRequest;
import com.triobase.service.openapi.dto.UpdateApplicationRequest;
import com.triobase.service.openapi.infrastructure.mapper.ApplicationClientMapper;
import com.triobase.service.openapi.infrastructure.mapper.ApplicationContactMapper;
import com.triobase.service.openapi.infrastructure.mapper.ApplicationOwnerMapper;
import com.triobase.service.openapi.infrastructure.mapper.IntegrationApplicationMapper;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.util.StringUtils;
import java.time.LocalDateTime;
import java.util.Set;

@Service @RequiredArgsConstructor
public class ApplicationManagementService {
 private final IntegrationApplicationMapper applicationMapper; private final ApplicationOwnerMapper ownerMapper;
 private final ApplicationContactMapper contactMapper; private final ApplicationClientMapper clientMapper;
 private final AssetApprovalService approvalService; private final IntegrationAuditService auditService; private final ObjectMapper objectMapper; private final PolicyChangeNotifier policyNotifier;
 @Transactional public ApplicationResponse create(CreateApplicationRequest r){if(r==null||!StringUtils.hasText(r.applicationKey())||!StringUtils.hasText(r.displayName())||!StringUtils.hasText(r.ownerId())||!StringUtils.hasText(r.purpose())||r.riskLevel()==null)throw invalid();String tenant=targetTenant(r.tenantId());if(tenant==null)throw invalid();if(applicationMapper.selectCount(new LambdaQueryWrapper<IntegrationApplication>().eq(IntegrationApplication::getApplicationKey,r.applicationKey()).eq(IntegrationApplication::getTenantId,tenant))>0)throw new BizException(40970,"OPENAPI_APPLICATION_EXISTS");IntegrationApplication a=new IntegrationApplication();a.setId(UlidGenerator.nextUlid());a.setTenantId(tenant);a.setApplicationKey(r.applicationKey().trim());a.setDisplayName(r.displayName().trim());a.setOwnerId(r.ownerId().trim());a.setPurpose(r.purpose().trim());a.setRiskLevel(r.riskLevel());a.setLifecycleState(ApplicationLifecycleState.DRAFT);a.setApprovalEvidence(objectMapper.createObjectNode());initialize(a);applicationMapper.insert(a);ApplicationOwner o=new ApplicationOwner();o.setId(UlidGenerator.nextUlid());o.setApplicationId(a.getId());o.setOwnerId(a.getOwnerId());o.setOwnerRole("PRIMARY");initialize(o);ownerMapper.insert(o);if(r.contacts()!=null)r.contacts().forEach(c->{ApplicationContact x=new ApplicationContact();x.setId(UlidGenerator.nextUlid());x.setApplicationId(a.getId());x.setContactRole(c.role());x.setContactName(c.name());x.setEmail(c.email());x.setPhone(c.phone());initialize(x);contactMapper.insert(x);});auditService.success("APPLICATION_CREATED","APPLICATION",a.getId(),JsonNodeFactory.instance.objectNode());return response(a);}
 @Transactional public ApplicationResponse update(String id,UpdateApplicationRequest r){if(r==null||!StringUtils.hasText(r.displayName())||!StringUtils.hasText(r.ownerId())||!StringUtils.hasText(r.purpose())||r.riskLevel()==null)throw invalid();IntegrationApplication a=requireApp(id);if(a.getLifecycleState()!=ApplicationLifecycleState.DRAFT&&a.getLifecycleState()!=ApplicationLifecycleState.PENDING_APPROVAL)throw new BizException(40970,"OPENAPI_APPLICATION_EDIT_REQUIRES_DRAFT");a.setDisplayName(r.displayName().trim());a.setOwnerId(r.ownerId().trim());a.setPurpose(r.purpose().trim());a.setRiskLevel(r.riskLevel());touch(a);applicationMapper.updateById(a);ownerMapper.delete(new LambdaQueryWrapper<ApplicationOwner>().eq(ApplicationOwner::getApplicationId,id).eq(ApplicationOwner::getOwnerRole,"PRIMARY"));ApplicationOwner o=new ApplicationOwner();o.setId(UlidGenerator.nextUlid());o.setApplicationId(a.getId());o.setOwnerId(a.getOwnerId());o.setOwnerRole("PRIMARY");initialize(o);ownerMapper.insert(o);auditService.success("APPLICATION_UPDATED","APPLICATION",id,JsonNodeFactory.instance.objectNode());return response(a);}
 @Transactional public ApplicationResponse submit(String id){IntegrationApplication a=requireApp(id);if(a.getLifecycleState()!=ApplicationLifecycleState.DRAFT)throw new BizException(40970,"OPENAPI_APPLICATION_NOT_DRAFT");Set<String> roles=a.getRiskLevel()==RiskLevel.HIGH||a.getRiskLevel()==RiskLevel.CRITICAL?Set.of("APPLICATION_OWNER","PLATFORM_ADMIN"):Set.of("APPLICATION_OWNER");approvalService.submit("APPLICATION",id,null,roles);a.setLifecycleState(ApplicationLifecycleState.PENDING_APPROVAL);touch(a);applicationMapper.updateById(a);return response(a);}
 @Transactional public ApplicationResponse activate(String id){IntegrationApplication a=requireApp(id);Set<String> roles=a.getRiskLevel()==RiskLevel.HIGH||a.getRiskLevel()==RiskLevel.CRITICAL?Set.of("APPLICATION_OWNER","PLATFORM_ADMIN"):Set.of("APPLICATION_OWNER");approvalService.requireApproved("APPLICATION",id,roles);a.setLifecycleState(ApplicationLifecycleState.ACTIVE);a.setApprovalEvidence(objectMapper.createObjectNode().put("approved",true));touch(a);applicationMapper.updateById(a);auditService.success("APPLICATION_ACTIVATED","APPLICATION",id,a.getApprovalEvidence());return response(a);}
 @Transactional public ApplicationResponse suspendApplication(String id,String reason){IntegrationApplication a=requireApp(id);if(a.getLifecycleState()!=ApplicationLifecycleState.ACTIVE)throw new BizException(40970,"OPENAPI_APPLICATION_NOT_ACTIVE");a.setLifecycleState(ApplicationLifecycleState.SUSPENDED);a.setSuspensionReason(StringUtils.hasText(reason)?reason:"OPERATOR_SUSPENSION");touch(a);applicationMapper.updateById(a);clientMapper.selectList(new LambdaQueryWrapper<ApplicationClient>().eq(ApplicationClient::getApplicationId,id).eq(ApplicationClient::getLifecycleState,ApplicationLifecycleState.ACTIVE)).forEach(c->{c.setLifecycleState(ApplicationLifecycleState.SUSPENDED);c.setSuspensionReason("PARENT_APPLICATION_SUSPENDED");touch(c);clientMapper.updateById(c);policyNotifier.publishAfterCommit(c.getTenantId(),c.getEnvironment());});return response(a);}
 @Transactional public ApplicationResponse reactivateApplication(String id){IntegrationApplication a=requireApp(id);if(a.getLifecycleState()!=ApplicationLifecycleState.SUSPENDED)throw new BizException(40970,"OPENAPI_APPLICATION_NOT_SUSPENDED");a.setLifecycleState(ApplicationLifecycleState.ACTIVE);a.setSuspensionReason(null);touch(a);applicationMapper.updateById(a);return response(a);}
 @Transactional public ApplicationResponse expireApplication(String id){return terminalApplication(id,ApplicationLifecycleState.EXPIRED,"APPLICATION_EXPIRED");}
 @Transactional public ApplicationResponse revokeApplication(String id){return terminalApplication(id,ApplicationLifecycleState.REVOKED,"APPLICATION_REVOKED");}
 @Transactional public ApplicationClientResponse createClient(String applicationId,CreateApplicationClientRequest r){IntegrationApplication a=requireApp(applicationId);if(a.getLifecycleState()!=ApplicationLifecycleState.ACTIVE||r==null||r.environment()==null||!StringUtils.hasText(r.clientKey()))throw invalid();if(clientMapper.selectCount(new LambdaQueryWrapper<ApplicationClient>().eq(ApplicationClient::getApplicationId,applicationId).eq(ApplicationClient::getEnvironment,r.environment()))>0)throw new BizException(40971,"OPENAPI_APPLICATION_ENVIRONMENT_CLIENT_EXISTS");ApplicationClient c=new ApplicationClient();c.setId(UlidGenerator.nextUlid());c.setApplicationId(applicationId);c.setTenantId(a.getTenantId());c.setEnvironment(r.environment());c.setClientKey(r.clientKey().trim());c.setNetworkPolicy(r.networkPolicy()==null?objectMapper.createObjectNode():r.networkPolicy().deepCopy());c.setSecurityPolicy(r.securityPolicy()==null?objectMapper.createObjectNode():r.securityPolicy().deepCopy());c.setExpiresAt(r.expiresAt());c.setSecurityViolationCount(0);c.setLifecycleState(r.environment()==Environment.PROD?ApplicationLifecycleState.PENDING_APPROVAL:ApplicationLifecycleState.ACTIVE);initialize(c);clientMapper.insert(c);if(r.environment()==Environment.PROD)approvalService.submit("APPLICATION_CLIENT",c.getId(),Environment.PROD,Set.of("APPLICATION_OWNER","PLATFORM_ADMIN"));auditService.success("APPLICATION_CLIENT_CREATED","APPLICATION_CLIENT",c.getId(),JsonNodeFactory.instance.objectNode().put("environment",r.environment().name()));return response(c);}
 @Transactional public ApplicationClientResponse activateClient(String id){ApplicationClient c=requireClient(id);requireApp(c.getApplicationId());if(c.getEnvironment()==Environment.PROD)approvalService.requireApproved("APPLICATION_CLIENT",id,Set.of("APPLICATION_OWNER","PLATFORM_ADMIN"));if(c.getExpiresAt()!=null&&!c.getExpiresAt().isAfter(LocalDateTime.now()))throw new BizException(40971,"OPENAPI_APPLICATION_CLIENT_EXPIRED");c.setLifecycleState(ApplicationLifecycleState.ACTIVE);c.setSuspensionReason(null);touch(c);clientMapper.updateById(c);auditService.success("APPLICATION_CLIENT_ACTIVATED","APPLICATION_CLIENT",id,JsonNodeFactory.instance.objectNode());return response(c);}
 @Transactional public ApplicationClientResponse suspendClient(String id,String reason){ApplicationClient c=requireClient(id);if(c.getLifecycleState()!=ApplicationLifecycleState.ACTIVE)throw new BizException(40971,"OPENAPI_APPLICATION_CLIENT_NOT_ACTIVE");c.setLifecycleState(ApplicationLifecycleState.SUSPENDED);c.setSuspensionReason(StringUtils.hasText(reason)?reason:"OPERATOR_SUSPENSION");touch(c);clientMapper.updateById(c);auditService.success("APPLICATION_CLIENT_SUSPENDED","APPLICATION_CLIENT",id,JsonNodeFactory.instance.objectNode().put("reason",c.getSuspensionReason()));policyNotifier.publishAfterCommit(c.getTenantId(),c.getEnvironment());return response(c);}
 @Transactional public ApplicationClientResponse reactivateClient(String id){ApplicationClient c=requireClient(id);if(c.getLifecycleState()!=ApplicationLifecycleState.SUSPENDED)throw new BizException(40971,"OPENAPI_APPLICATION_CLIENT_NOT_SUSPENDED");return activateClient(id);}
 @Transactional public ApplicationClientResponse expireClient(String id){return terminal(id,ApplicationLifecycleState.EXPIRED,"APPLICATION_CLIENT_EXPIRED");}
 @Transactional public ApplicationClientResponse revokeClient(String id){return terminal(id,ApplicationLifecycleState.REVOKED,"APPLICATION_CLIENT_REVOKED");}
 public ApplicationResponse get(String id){return response(requireApp(id));} public ApplicationClientResponse getClient(String id){return response(requireClient(id));}
 private ApplicationClientResponse terminal(String id,ApplicationLifecycleState state,String event){ApplicationClient c=requireClient(id);c.setLifecycleState(state);touch(c);clientMapper.updateById(c);auditService.success(event,"APPLICATION_CLIENT",id,JsonNodeFactory.instance.objectNode());policyNotifier.publishAfterCommit(c.getTenantId(),c.getEnvironment());return response(c);}
 private ApplicationResponse terminalApplication(String id,ApplicationLifecycleState state,String event){IntegrationApplication a=requireApp(id);a.setLifecycleState(state);touch(a);applicationMapper.updateById(a);clientMapper.selectList(new LambdaQueryWrapper<ApplicationClient>().eq(ApplicationClient::getApplicationId,id)).forEach(c->{if(c.getLifecycleState()!=ApplicationLifecycleState.REVOKED&&c.getLifecycleState()!=ApplicationLifecycleState.EXPIRED){c.setLifecycleState(state);touch(c);clientMapper.updateById(c);policyNotifier.publishAfterCommit(c.getTenantId(),c.getEnvironment());}});auditService.success(event,"APPLICATION",id,JsonNodeFactory.instance.objectNode());return response(a);}
 private IntegrationApplication requireApp(String id){IntegrationApplication a=applicationMapper.selectById(id);String t=SecurityContextHolder.getTenantId();if(a==null||(t!=null&&!t.equals(a.getTenantId())))throw new BizException(40470,"OPENAPI_APPLICATION_NOT_FOUND");return a;} private ApplicationClient requireClient(String id){ApplicationClient c=clientMapper.selectById(id);String t=SecurityContextHolder.getTenantId();if(c==null||(t!=null&&!t.equals(c.getTenantId())))throw new BizException(40471,"OPENAPI_APPLICATION_CLIENT_NOT_FOUND");return c;}
 private ApplicationResponse response(IntegrationApplication a){return new ApplicationResponse(a.getId(),a.getTenantId(),a.getApplicationKey(),a.getDisplayName(),a.getOwnerId(),a.getPurpose(),a.getRiskLevel(),a.getLifecycleState(),a.getSuspensionReason());} private ApplicationClientResponse response(ApplicationClient c){return new ApplicationClientResponse(c.getId(),c.getApplicationId(),c.getTenantId(),c.getEnvironment(),c.getClientKey(),c.getLifecycleState(),c.getNetworkPolicy(),c.getSecurityPolicy(),c.getExpiresAt(),c.getSuspensionReason());}
 private BizException invalid(){return new BizException(40070,"OPENAPI_APPLICATION_REQUEST_INVALID");} private String targetTenant(String r){String c=SecurityContextHolder.getTenantId();if(c==null)return StringUtils.hasText(r)?r.trim():null;if(StringUtils.hasText(r)&&!c.equals(r.trim()))throw new BizException(40310,"OPENAPI_CROSS_TENANT_ACCESS_DENIED");return c;}
 private void initialize(com.triobase.common.core.entity.BaseEntity e){LocalDateTime n=LocalDateTime.now();e.setCreatedBy(operator());e.setCreatedAt(n);e.setUpdatedBy(operator());e.setUpdatedAt(n);if(e instanceof com.triobase.service.openapi.domain.model.VersionedEntity v)v.setRowVersion(0L);}private void touch(com.triobase.common.core.entity.BaseEntity e){e.setUpdatedBy(operator());e.setUpdatedAt(LocalDateTime.now());}private String operator(){return StringUtils.hasText(SecurityContextHolder.getUserId())?SecurityContextHolder.getUserId():"SYSTEM";}
}
