package com.triobase.service.openapi.service;
import com.baomidou.mybatisplus.core.conditions.query.LambdaQueryWrapper;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.node.ArrayNode;
import com.fasterxml.jackson.databind.node.JsonNodeFactory;
import com.fasterxml.jackson.databind.node.ObjectNode;
import com.triobase.common.core.context.SecurityContextHolder;
import com.triobase.common.core.exception.BizException;
import com.triobase.common.core.id.UlidGenerator;
import com.triobase.service.openapi.domain.entity.ApiProduct;
import com.triobase.service.openapi.domain.entity.ApiProductAccessGrant;
import com.triobase.service.openapi.domain.entity.ApiProductRouteMember;
import com.triobase.service.openapi.domain.entity.ApiProductVersion;
import com.triobase.service.openapi.domain.entity.ApplicationClient;
import com.triobase.service.openapi.domain.entity.ProductSubscription;
import com.triobase.service.openapi.domain.entity.SubscriptionRouteOverride;
import com.triobase.service.openapi.domain.enums.ApplicationLifecycleState;
import com.triobase.service.openapi.domain.enums.Environment;
import com.triobase.service.openapi.domain.enums.ProductVisibility;
import com.triobase.service.openapi.domain.enums.SubscriptionLifecycleState;
import com.triobase.service.openapi.domain.enums.VersionLifecycleState;
import com.triobase.service.openapi.dto.CreateSubscriptionRequest;
import com.triobase.service.openapi.dto.SubscriptionResponse;
import com.triobase.service.openapi.dto.SubscriptionRouteOverrideRequest;
import com.triobase.service.openapi.infrastructure.mapper.ApiProductAccessGrantMapper;
import com.triobase.service.openapi.infrastructure.mapper.ApiProductMapper;
import com.triobase.service.openapi.infrastructure.mapper.ApiProductRouteMemberMapper;
import com.triobase.service.openapi.infrastructure.mapper.ApiProductVersionMapper;
import com.triobase.service.openapi.infrastructure.mapper.ApplicationClientMapper;
import com.triobase.service.openapi.infrastructure.mapper.ProductSubscriptionMapper;
import com.triobase.service.openapi.infrastructure.mapper.SubscriptionRouteOverrideMapper;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.util.StringUtils;
import java.time.LocalDateTime;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;

@Service @RequiredArgsConstructor
public class ProductSubscriptionService {
 private final ProductSubscriptionMapper subscriptionMapper;private final SubscriptionRouteOverrideMapper overrideMapper;
 private final ApplicationClientMapper clientMapper;private final ApiProductVersionMapper versionMapper;private final ApiProductMapper productMapper;
 private final ApiProductRouteMemberMapper memberMapper;private final ApiProductAccessGrantMapper grantMapper;
 private final PolicyRestrictionValidator restrictionValidator;private final AssetApprovalService approvalService;
 private final IntegrationAuditService auditService;private final ObjectMapper objectMapper;private final PolicyChangeNotifier policyNotifier;
 @Transactional public SubscriptionResponse request(CreateSubscriptionRequest r){if(r==null||!StringUtils.hasText(r.applicationClientId())||!StringUtils.hasText(r.apiProductVersionId())||invalidWindow(r.effectiveFrom(),r.effectiveUntil()))throw invalid();ApplicationClient c=requireClient(r.applicationClientId());ApiProductVersion v=requirePublishedVersion(r.apiProductVersionId());ApiProduct p=requireVisibleProduct(v.getApiProductId(),c);restrictionValidator.requireSubset(r.requestedScopes(),v.getScopes(),"OPENAPI_SUBSCRIPTION_SCOPE_NOT_IN_PRODUCT");ProductSubscription s=new ProductSubscription();s.setId(UlidGenerator.nextUlid());s.setTenantId(c.getTenantId());s.setApplicationClientId(c.getId());s.setApiProductVersionId(v.getId());s.setEnvironment(c.getEnvironment());s.setLifecycleState(SubscriptionLifecycleState.PENDING_APPROVAL);s.setRequestedScopes(copyArray(r.requestedScopes()));s.setEffectiveScopes(copyArray(r.requestedScopes()));s.setOverrides(objectMapper.createObjectNode());s.setEffectiveFrom(r.effectiveFrom());s.setEffectiveUntil(r.effectiveUntil());s.setRequestedBy(operator());initialize(s);subscriptionMapper.insert(s);replaceOverrides(s,v,r.routeOverrides());Set<String> roles=c.getEnvironment()==Environment.PROD?Set.of("ASSET_OWNER","PLATFORM_ADMIN"):Set.of("ASSET_OWNER");approvalService.submit("PRODUCT_SUBSCRIPTION",s.getId(),c.getEnvironment(),roles);auditService.success("PRODUCT_SUBSCRIPTION_REQUESTED","PRODUCT_SUBSCRIPTION",s.getId(),JsonNodeFactory.instance.objectNode().put("productId",p.getId()));return response(s);}
 @Transactional public SubscriptionResponse activate(String id){ProductSubscription s=requireSubscription(id);Set<String> roles=s.getEnvironment()==Environment.PROD?Set.of("ASSET_OWNER","PLATFORM_ADMIN"):Set.of("ASSET_OWNER");approvalService.requireApproved("PRODUCT_SUBSCRIPTION",id,roles);if(s.getEffectiveUntil()!=null&&!s.getEffectiveUntil().isAfter(LocalDateTime.now()))throw new BizException(40980,"OPENAPI_SUBSCRIPTION_EXPIRED");s.setLifecycleState(SubscriptionLifecycleState.ACTIVE);s.setActivatedAt(LocalDateTime.now());touch(s);subscriptionMapper.updateById(s);audit("PRODUCT_SUBSCRIPTION_ACTIVATED",s);policyNotifier.publishAfterCommit(s.getTenantId(),s.getEnvironment());return response(s);}
 @Transactional public SubscriptionResponse requestUpgrade(String id,String newProductVersionId){ProductSubscription old=requireSubscription(id);if(old.getLifecycleState()!=SubscriptionLifecycleState.ACTIVE)throw new BizException(40980,"OPENAPI_SUBSCRIPTION_NOT_ACTIVE");CreateSubscriptionRequest request=new CreateSubscriptionRequest(old.getApplicationClientId(),newProductVersionId,old.getEffectiveScopes(),List.of(),old.getEffectiveFrom(),old.getEffectiveUntil());return request(request);}
 @Transactional public SubscriptionResponse suspend(String id,String reason){ProductSubscription s=requireSubscription(id);s.setLifecycleState(SubscriptionLifecycleState.SUSPENDED);s.setSuspensionReason(StringUtils.hasText(reason)?reason:"OPERATOR_SUSPENSION");touch(s);subscriptionMapper.updateById(s);audit("PRODUCT_SUBSCRIPTION_SUSPENDED",s);policyNotifier.publishAfterCommit(s.getTenantId(),s.getEnvironment());return response(s);}
 @Transactional public SubscriptionResponse revoke(String id){ProductSubscription s=requireSubscription(id);s.setLifecycleState(SubscriptionLifecycleState.REVOKED);touch(s);subscriptionMapper.updateById(s);audit("PRODUCT_SUBSCRIPTION_REVOKED",s);policyNotifier.publishAfterCommit(s.getTenantId(),s.getEnvironment());return response(s);}
 @Transactional public SubscriptionResponse expire(String id){ProductSubscription s=requireSubscription(id);s.setLifecycleState(SubscriptionLifecycleState.EXPIRED);touch(s);subscriptionMapper.updateById(s);return response(s);}
 public ProductSubscription requireActiveAccess(String clientId,String routeKey,String operation,Set<String> requiredScopes,LocalDateTime at){ApplicationClient c=requireClient(clientId);List<ProductSubscription> active=subscriptionMapper.selectList(new LambdaQueryWrapper<ProductSubscription>().eq(ProductSubscription::getApplicationClientId,clientId).eq(ProductSubscription::getEnvironment,c.getEnvironment()).eq(ProductSubscription::getLifecycleState,SubscriptionLifecycleState.ACTIVE));for(ProductSubscription s:active){if(!within(s,at))continue;ApiProductRouteMember m=memberMapper.selectOne(new LambdaQueryWrapper<ApiProductRouteMember>().eq(ApiProductRouteMember::getApiProductVersionId,s.getApiProductVersionId()).eq(ApiProductRouteMember::getRouteKey,routeKey));if(m==null)continue;SubscriptionRouteOverride o=overrideMapper.selectOne(new LambdaQueryWrapper<SubscriptionRouteOverride>().eq(SubscriptionRouteOverride::getSubscriptionId,s.getId()).eq(SubscriptionRouteOverride::getRouteKey,routeKey));if(o!=null&&Boolean.TRUE.equals(o.getExcluded()))continue;Set<String> operations=restrictionValidator.textSet(o!=null&&!o.getAllowedOperations().isEmpty()?o.getAllowedOperations():m.getOperations());if(!operations.isEmpty()&&!operations.contains(operation))continue;Set<String> scopes=restrictionValidator.textSet(s.getEffectiveScopes());if(scopes.containsAll(requiredScopes))return s;}throw new BizException(40380,"OPENAPI_SUBSCRIPTION_ACCESS_DENIED");}
 public ProductSubscription requireRuntimeAccess(String clientId,String subscriptionId,String routeKey,String operation,LocalDateTime at){ApplicationClient c=requireClient(clientId);ProductSubscription s=subscriptionMapper.selectById(subscriptionId);if(s==null||!clientId.equals(s.getApplicationClientId())||s.getEnvironment()!=c.getEnvironment()||s.getLifecycleState()!=SubscriptionLifecycleState.ACTIVE||!within(s,at)||!c.getTenantId().equals(s.getTenantId()))throw new BizException(40380,"OPENAPI_SUBSCRIPTION_ACCESS_DENIED");ApiProductRouteMember m=memberMapper.selectOne(new LambdaQueryWrapper<ApiProductRouteMember>().eq(ApiProductRouteMember::getApiProductVersionId,s.getApiProductVersionId()).eq(ApiProductRouteMember::getRouteKey,routeKey));if(m==null)throw new BizException(40380,"OPENAPI_SUBSCRIPTION_ACCESS_DENIED");SubscriptionRouteOverride o=overrideMapper.selectOne(new LambdaQueryWrapper<SubscriptionRouteOverride>().eq(SubscriptionRouteOverride::getSubscriptionId,s.getId()).eq(SubscriptionRouteOverride::getRouteKey,routeKey));if(o!=null&&Boolean.TRUE.equals(o.getExcluded()))throw new BizException(40380,"OPENAPI_SUBSCRIPTION_ACCESS_DENIED");Set<String> operations=restrictionValidator.textSet(o!=null&&!o.getAllowedOperations().isEmpty()?o.getAllowedOperations():m.getOperations());if(!operations.isEmpty()&&StringUtils.hasText(operation)&&!operations.contains(operation))throw new BizException(40380,"OPENAPI_SUBSCRIPTION_ACCESS_DENIED");return s;}
 private void replaceOverrides(ProductSubscription s,ApiProductVersion v,List<SubscriptionRouteOverrideRequest> requests){if(requests==null)return;Map<String,ApiProductRouteMember> members=new HashMap<>();memberMapper.selectList(new LambdaQueryWrapper<ApiProductRouteMember>().eq(ApiProductRouteMember::getApiProductVersionId,v.getId())).forEach(m->members.put(m.getRouteKey(),m));ObjectNode aggregate=objectMapper.createObjectNode();for(SubscriptionRouteOverrideRequest r:requests){ApiProductRouteMember m=members.get(r.routeKey());if(m==null)throw new BizException(40980,"OPENAPI_SUBSCRIPTION_OVERRIDE_ROUTE_NOT_IN_PRODUCT");restrictionValidator.requireSubset(r.allowedOperations(),m.getOperations(),"OPENAPI_SUBSCRIPTION_OVERRIDE_BROADENS_OPERATION");restrictionValidator.requireSubset(r.requiredScopes(),v.getScopes(),"OPENAPI_SUBSCRIPTION_OVERRIDE_BROADENS_SCOPE");restrictionValidator.requireSubset(r.structureVersionIds(),m.getCanonicalStructureVersionIds(),"OPENAPI_SUBSCRIPTION_OVERRIDE_BROADENS_STRUCTURE");JsonNode baseNetworks=v.getSecurityPolicy()==null?null:v.getSecurityPolicy().get("allowedNetworks");if(baseNetworks!=null&&!baseNetworks.isEmpty())restrictionValidator.requireSubset(r.sourceNetworks(),baseNetworks,"OPENAPI_SUBSCRIPTION_OVERRIDE_BROADENS_NETWORK");restrictionValidator.requireStricterLimits(r.quotaOverride(),v.getTrafficPolicy());if(r.fieldRestrictions()!=null&&r.fieldRestrictions().path("allowAll").asBoolean(false))throw new BizException(40980,"OPENAPI_SUBSCRIPTION_OVERRIDE_BROADENS_FIELDS");SubscriptionRouteOverride o=new SubscriptionRouteOverride();o.setId(UlidGenerator.nextUlid());o.setSubscriptionId(s.getId());o.setRouteKey(r.routeKey());o.setExcluded(r.excluded());o.setAllowedOperations(copyArray(r.allowedOperations()));o.setRequiredScopes(copyArray(r.requiredScopes()));o.setQuotaOverride(copyObject(r.quotaOverride()));o.setSourceNetworks(copyArray(r.sourceNetworks()));o.setStructureVersionIds(copyArray(r.structureVersionIds()));o.setFieldRestrictions(copyObject(r.fieldRestrictions()));initialize(o);overrideMapper.insert(o);aggregate.set(r.routeKey(),objectMapper.valueToTree(r));}s.setOverrides(aggregate);subscriptionMapper.updateById(s);}
 private ApiProduct requireVisibleProduct(String id,ApplicationClient c){ApiProduct p=productMapper.selectById(id);if(p==null)throw new BizException(40460,"OPENAPI_PRODUCT_NOT_FOUND");boolean visible=p.getVisibility()==ProductVisibility.PLATFORM_PUBLIC||(p.getVisibility()==ProductVisibility.TENANT&&c.getTenantId().equals(p.getTenantId()))||(p.getVisibility()==ProductVisibility.PRIVATE&&grantMapper.selectCount(new LambdaQueryWrapper<ApiProductAccessGrant>().eq(ApiProductAccessGrant::getApiProductId,id).eq(ApiProductAccessGrant::getGranteeType,"APPLICATION").eq(ApiProductAccessGrant::getGranteeId,c.getApplicationId()))>0);if(!visible)throw new BizException(40460,"OPENAPI_PRODUCT_NOT_FOUND");return p;}
 private ApplicationClient requireClient(String id){ApplicationClient c=clientMapper.selectById(id);String t=SecurityContextHolder.getTenantId();if(c==null||(t!=null&&!t.equals(c.getTenantId()))||c.getLifecycleState()!=ApplicationLifecycleState.ACTIVE)throw new BizException(40471,"OPENAPI_ACTIVE_APPLICATION_CLIENT_NOT_FOUND");return c;}private ApiProductVersion requirePublishedVersion(String id){ApiProductVersion v=versionMapper.selectById(id);if(v==null||v.getLifecycleState()!=VersionLifecycleState.PUBLISHED)throw new BizException(40461,"OPENAPI_PUBLISHED_PRODUCT_VERSION_NOT_FOUND");return v;}private ProductSubscription requireSubscription(String id){ProductSubscription s=subscriptionMapper.selectById(id);String t=SecurityContextHolder.getTenantId();if(s==null||(t!=null&&!t.equals(s.getTenantId())))throw new BizException(40480,"OPENAPI_SUBSCRIPTION_NOT_FOUND");return s;}
 private boolean within(ProductSubscription s,LocalDateTime at){LocalDateTime x=at==null?LocalDateTime.now():at;return(s.getEffectiveFrom()==null||!x.isBefore(s.getEffectiveFrom()))&&(s.getEffectiveUntil()==null||x.isBefore(s.getEffectiveUntil()));}private boolean invalidWindow(LocalDateTime f,LocalDateTime u){return f!=null&&u!=null&&!u.isAfter(f);}private BizException invalid(){return new BizException(40080,"OPENAPI_SUBSCRIPTION_REQUEST_INVALID");}
 private ArrayNode copyArray(JsonNode n){return n!=null&&n.isArray()?(ArrayNode)n.deepCopy():objectMapper.createArrayNode();}private JsonNode copyObject(JsonNode n){return n!=null&&n.isObject()?n.deepCopy():objectMapper.createObjectNode();}private SubscriptionResponse response(ProductSubscription s){return new SubscriptionResponse(s.getId(),s.getTenantId(),s.getApplicationClientId(),s.getApiProductVersionId(),s.getEnvironment(),s.getLifecycleState(),s.getEffectiveScopes(),s.getOverrides(),s.getEffectiveFrom(),s.getEffectiveUntil(),s.getSuspensionReason());}
 private void audit(String event,ProductSubscription s){auditService.success(event,"PRODUCT_SUBSCRIPTION",s.getId(),JsonNodeFactory.instance.objectNode().put("clientId",s.getApplicationClientId()));}private void initialize(com.triobase.common.core.entity.BaseEntity e){LocalDateTime n=LocalDateTime.now();e.setCreatedBy(operator());e.setCreatedAt(n);e.setUpdatedBy(operator());e.setUpdatedAt(n);if(e instanceof com.triobase.service.openapi.domain.model.VersionedEntity v)v.setRowVersion(0L);}private void touch(com.triobase.common.core.entity.BaseEntity e){e.setUpdatedBy(operator());e.setUpdatedAt(LocalDateTime.now());}private String operator(){return StringUtils.hasText(SecurityContextHolder.getUserId())?SecurityContextHolder.getUserId():"SYSTEM";}
}
