"""注释治理扫描器的结构、排除和增量规则测试。"""

from __future__ import annotations

import importlib.util
import sys
import tempfile
import unittest
from pathlib import Path


SCRIPT = Path(__file__).parents[1] / "scripts" / "comment_governance.py"
SPEC = importlib.util.spec_from_file_location("comment_governance", SCRIPT)
MODULE = importlib.util.module_from_spec(SPEC)
assert SPEC.loader is not None
sys.modules[SPEC.name] = MODULE
SPEC.loader.exec_module(MODULE)


class CommentGovernanceTest(unittest.TestCase):

    def test_java_public_type_without_javadoc_is_advisory(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            path = root / "Example.java"
            path.write_text("public class Example {}\n", encoding="utf-8")
            findings = MODULE.scan_file(root, path)
            self.assertEqual(["CG-B001"], [item.rule_id for item in findings])

    def test_valid_javadoc_avoids_public_type_finding(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            path = root / "Example.java"
            path.write_text("/** Explains the contract. */\npublic class Example {}\n", encoding="utf-8")
            self.assertEqual([], MODULE.scan_file(root, path))

    def test_todo_requires_owner_and_removal_condition(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            path = root / "module.py"
            path.write_text('"""Module."""\n# TODO: later\n', encoding="utf-8")
            findings = MODULE.scan_file(root, path)
            self.assertIn("CG-P003", [item.rule_id for item in findings])

    def test_generated_file_is_excluded(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            path = root / "Generated.java"
            path.write_text("// Generated by fixture. DO NOT EDIT MANUALLY.\npublic class Generated {}\n", encoding="utf-8")
            self.assertEqual([], MODULE.scan_file(root, path))

    def test_build_and_vendor_directories_are_excluded(self) -> None:
        self.assertTrue(MODULE.is_excluded(Path("module/target/Generated.java")))
        self.assertTrue(MODULE.is_excluded(Path("vendor/library.py")))
        self.assertFalse(MODULE.is_excluded(Path("src/main/App.java")))

    def test_invalid_suppression_has_stable_blocking_rule(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            path = root / "Example.java"
            path.write_text(
                "// comment-governance-disable-next-line CG-B001\npublic class Example {}\n",
                encoding="utf-8",
            )
            findings = MODULE.scan_file(root, path)
            violation = next(item for item in findings if item.rule_id == "CG-B005")
            self.assertEqual("BLOCKER", violation.severity)
            self.assertEqual(1, violation.line)
            self.assertIn("负责人", violation.remediation)

    def test_report_contains_wave_owner_and_location(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            output = Path(directory) / "report.json"
            finding = MODULE.Finding("CG-A001", "ADVISORY", "trio-base-services/service-auth/A.java", 7, "missing", "fix")
            MODULE.write_report(output, [finding])
            report = __import__("json").loads(output.read_text(encoding="utf-8"))
            item = report["findings"][0]
            self.assertEqual("wave-1", item["remediationWave"])
            self.assertEqual("service-team", item["owner"])
            self.assertEqual(7, item["line"])

    def test_exported_typescript_contract_requires_tsdoc(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            path = root / "client.ts"
            path.write_text("export interface Client {}\n", encoding="utf-8")
            findings = MODULE.scan_file(root, path)
            self.assertIn("CG-B001", [item.rule_id for item in findings])

    def test_documented_typescript_contract_is_accepted(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            path = root / "client.ts"
            path.write_text("/**\n * Governed client contract.\n */\nexport interface Client {}\n", encoding="utf-8")
            self.assertEqual([], MODULE.scan_file(root, path))

    def test_risky_sql_requires_purpose_and_rollback(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            path = root / "V1__change.sql"
            path.write_text("ALTER TABLE example ADD COLUMN value text;\n", encoding="utf-8")
            findings = MODULE.scan_file(root, path)
            self.assertEqual(2, len([item for item in findings if item.rule_id == "CG-B002"]))

    def test_commented_code_and_restatement_are_prohibited(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            path = root / "Example.java"
            path.write_text("// return oldValue;\n// 返回结果\n", encoding="utf-8")
            rules = {item.rule_id for item in MODULE.scan_file(root, path)}
            self.assertIn("CG-P002", rules)
            self.assertIn("CG-P004", rules)

    def test_new_public_contract_blocks_but_baseline_debt_does_not(self) -> None:
        finding = MODULE.Finding("CG-B001", "BLOCKER", "src/NewContract.java", 3, "missing NewContract", "fix")
        self.assertEqual([finding], MODULE.new_blocking_findings([finding], set()))
        self.assertEqual([], MODULE.new_blocking_findings([finding], {finding.fingerprint}))


if __name__ == "__main__":
    unittest.main()
